import { db } from "@/lib/db";

// ============================================================
// Case & transfer identity generation (spec §3/§20).
// Format: CASE-<STATE>-<DISTRICT>-<YEAR>-<000001>
//         TRF-<STATE>-<DISTRICT>-<YEAR>-<000001>
// - Generated by the backend only; never accepted from the client.
// - Immutable once issued; independent of custodian.
// - Retry-on-conflict guards concurrent creation (same pattern
//   as Phase 1 department/officer ID generation).
//
// SEQUENCE CORRECTNESS: candidates derive from the MAX numeric
// suffix already issued for the prefix — never from a row count.
// A count-based sequence silently breaks when the data has gaps
// (hard-deleted cases/rows in maintenance or test flows): count+1
// can point at an existing id, every retry recomputes the same
// dead candidate, and generation falls to the timestamp fallback,
// violating the documented fixed-width format (observed as
// OFF-/DOC- ids like `...-55657798` after deletes).
//
// The geo parameter is structurally typed (IdGeo) so callers can
// pass either a full ResolvedGeo (case creation) or a light
// projection of the case's stored geography (documents/evidence,
// which inherit the case's geo).
// ============================================================

export interface IdGeo {
  state: { code: string };
  district: { code: string };
}

function pad(n: number, width: number): string {
  return String(n).padStart(width, "0");
}

function districtFragment(geo: IdGeo): string {
  return geo.district.code.replace(/[^A-Za-z0-9]/g, "").slice(0, 4).toUpperCase() || "XXXX";
}

function stateFragment(geo: IdGeo): string {
  return geo.state.code.replace(/[^A-Za-z0-9]/g, "").slice(0, 4).toUpperCase() || "XXXX";
}

/**
 * Max-suffix sequence generator shared by all case-domain ids.
 * `loadExisting` returns every id sharing the prefix (only the
 * numeric suffix of each is inspected — non-numeric fallback ids
 * from the safety net are ignored for sequencing but counted by
 * max, since parse skips them).
 */
async function nextSequenceId(
  prefix: string,
  width: number,
  loadExisting: () => Promise<string[]>,
  exists: (candidate: string) => Promise<boolean>
): Promise<string> {
  for (let attempt = 0; attempt < 5; attempt++) {
    const ids = await loadExisting();
    let max = 0;
    for (const id of ids) {
      const suffix = id.slice(prefix.length);
      // Only WELL-FORMED suffixes (exact width) drive the sequence —
      // legacy/timestamp fallback ids must not poison the format.
      if (new RegExp(`^\\d{${width}}$`).test(suffix)) {
        const value = parseInt(suffix, 10);
        if (Number.isFinite(value) && value > max) max = value;
      }
    }
    const candidate = `${prefix}${pad(max + 1, 6)}`;
    if (!(await exists(candidate))) return candidate;
  }
  return `${prefix}${Date.now().toString().slice(-9)}`;
}

export async function generateCaseId(geo: IdGeo, year: number): Promise<string> {
  const prefix = `CASE-${stateFragment(geo)}-${districtFragment(geo)}-${year}-`;
  return nextSequenceId(
    prefix,
    6,
    async () =>
      (
        await db.case.findMany({
          where: { caseId: { startsWith: prefix } },
          select: { caseId: true },
        })
      ).map((r) => r.caseId),
    async (candidate) => !!(await db.case.findUnique({ where: { caseId: candidate } }))
  );
}

export async function generateTransferId(geo: IdGeo, year: number): Promise<string> {
  const prefix = `TRF-${stateFragment(geo)}-${districtFragment(geo)}-${year}-`;
  return nextSequenceId(
    prefix,
    6,
    async () =>
      (
        await db.caseTransfer.findMany({
          where: { transferId: { startsWith: prefix } },
          select: { transferId: true },
        })
      ).map((r) => r.transferId),
    async (candidate) => !!(await db.caseTransfer.findUnique({ where: { transferId: candidate } }))
  );
}

// ------------------------------------------------------------
// PHASE 3 — document & evidence identity. Documents/evidence
// inherit the case's geography; generation follows the same
// backend-only, retry-on-conflict pattern.
// ------------------------------------------------------------

export async function generateDocumentId(geo: IdGeo, year: number): Promise<string> {
  const prefix = `DOC-${stateFragment(geo)}-${districtFragment(geo)}-${year}-`;
  return nextSequenceId(
    prefix,
    6,
    async () =>
      (
        await db.caseDocument.findMany({
          where: { documentId: { startsWith: prefix } },
          select: { documentId: true },
        })
      ).map((r) => r.documentId),
    async (candidate) => !!(await db.caseDocument.findUnique({ where: { documentId: candidate } }))
  );
}

// ------------------------------------------------------------
// PHASE 4 — evidence identity (spec §4): EVD-<STATE>-<DIST>-
// <YEAR>-<000001>, backend-generated, immutable, NEVER a filename
// or external reference. Evidence transfers: ETR-*. Ledger anchors
// are not geo-scoped: ANCHOR-<YEAR>-<000001>.
// ------------------------------------------------------------

export async function generateEvidenceId(geo: IdGeo, year: number): Promise<string> {
  const prefix = `EVD-${stateFragment(geo)}-${districtFragment(geo)}-${year}-`;
  return nextSequenceId(
    prefix,
    6,
    async () =>
      (
        await db.evidence.findMany({
          where: { evidenceId: { startsWith: prefix } },
          select: { evidenceId: true },
        })
      ).map((r) => r.evidenceId),
    async (candidate) => !!(await db.evidence.findUnique({ where: { evidenceId: candidate } }))
  );
}

export async function generateEvidenceTransferId(geo: IdGeo, year: number): Promise<string> {
  const prefix = `ETR-${stateFragment(geo)}-${districtFragment(geo)}-${year}-`;
  return nextSequenceId(
    prefix,
    6,
    async () =>
      (
        await db.evidenceTransfer.findMany({
          where: { transferId: { startsWith: prefix } },
          select: { transferId: true },
        })
      ).map((r) => r.transferId),
    async (candidate) => !!(await db.evidenceTransfer.findUnique({ where: { transferId: candidate } }))
  );
}

export async function generateAnchorId(year: number): Promise<string> {
  const prefix = `ANCHOR-${year}-`;
  return nextSequenceId(
    prefix,
    6,
    async () =>
      (
        await db.ledgerAnchor.findMany({
          where: { anchorId: { startsWith: prefix } },
          select: { anchorId: true },
        })
      ).map((r) => r.anchorId),
    async (candidate) => !!(await db.ledgerAnchor.findUnique({ where: { anchorId: candidate } }))
  );
}

// Phase 5 — AI processing job ids (AIJ-2026-NNNNNN). Year-scoped,
// sequence from the max well-formed suffix (same correctness rule
// as every generator in this module).
export async function generateAIJobId(): Promise<string> {
  const year = new Date().getUTCFullYear();
  const prefix = `AIJ-${year}-`;
  return nextSequenceId(
    prefix,
    6,
    async () =>
      (
        await db.aIProcessingJob.findMany({
          where: { jobId: { startsWith: prefix } },
          select: { jobId: true },
        })
      ).map((r) => r.jobId),
    async (candidate) => !!(await db.aIProcessingJob.findUnique({ where: { jobId: candidate } }))
  );
}
