import { db } from "@/lib/db";
import { geoCodeFragments, type ResolvedGeo } from "@/lib/geo";

// ============================================================
// Case & transfer identity generation (spec §3/§20).
// Format: CASE-<STATE>-<DISTRICT>-<YEAR>-<000001>
//         TRF-<STATE>-<DISTRICT>-<YEAR>-<000001>
// - Generated by the backend only; never accepted from the client.
// - Immutable once issued; independent of custodian.
// - Retry-on-conflict guards concurrent creation (same pattern
//   as Phase 1 department/officer ID generation).
// ============================================================

function pad(n: number, width: number): string {
  return String(n).padStart(width, "0");
}

function districtFragment(geo: ResolvedGeo): string {
  return geo.district.code.replace(/[^A-Za-z0-9]/g, "").slice(0, 4).toUpperCase() || "XXXX";
}

export async function generateCaseId(geo: ResolvedGeo, year: number): Promise<string> {
  const { stateCode } = geoCodeFragments(geo);
  const prefix = `CASE-${stateCode}-${districtFragment(geo)}-${year}-`;

  for (let attempt = 0; attempt < 5; attempt++) {
    const count = await db.case.count({
      where: { caseId: { startsWith: prefix } },
    });
    const candidate = `${prefix}${pad(count + 1, 6)}`;
    const exists = await db.case.findUnique({ where: { caseId: candidate } });
    if (!exists) return candidate;
  }
  return `${prefix}${Date.now().toString().slice(-9)}`;
}

export async function generateTransferId(geo: ResolvedGeo, year: number): Promise<string> {
  const { stateCode } = geoCodeFragments(geo);
  const prefix = `TRF-${stateCode}-${districtFragment(geo)}-${year}-`;

  for (let attempt = 0; attempt < 5; attempt++) {
    const count = await db.caseTransfer.count({
      where: { transferId: { startsWith: prefix } },
    });
    const candidate = `${prefix}${pad(count + 1, 6)}`;
    const exists = await db.caseTransfer.findUnique({ where: { transferId: candidate } });
    if (!exists) return candidate;
  }
  return `${prefix}${Date.now().toString().slice(-9)}`;
}
