"use client";

import * as React from "react";
import { api, ApiClientError } from "@/lib/client/api";
import { useAuth } from "@/lib/client/store";
import { GeographicSelector, type GeoSelection } from "@/components/platform/GeographicSelector";
import { Button } from "@/components/ui/button";
import { Input } from "@/components/ui/input";
import { Label } from "@/components/ui/label";
import { Textarea } from "@/components/ui/textarea";
import { Card, CardContent, CardDescription, CardHeader, CardTitle } from "@/components/ui/card";
import { Select, SelectContent, SelectItem, SelectTrigger, SelectValue } from "@/components/ui/select";
import { Separator } from "@/components/ui/separator";
import { ErrorState, FieldError } from "@/components/platform/common";
import { Gavel, CheckCircle2 } from "lucide-react";

// ============================================================
// Case creation form (spec §16/§40): Identity → Classification
// → Location → Review. The originating department and creator
// are derived server-side from the session and only shown here.
// ============================================================

export function CaseCreateView({ onCreated }: { onCreated: (caseId: string) => void }) {
  const { me, meta } = useAuth();

  const [title, setTitle] = React.useState("");
  const [caseNumber, setCaseNumber] = React.useState("");
  const [description, setDescription] = React.useState("");
  const [caseType, setCaseType] = React.useState("");
  const [caseCategory, setCaseCategory] = React.useState("");
  const [priority, setPriority] = React.useState("");
  const [geo, setGeo] = React.useState<GeoSelection>({});
  const [confirming, setConfirming] = React.useState(false);

  const [error, setError] = React.useState<string | null>(null);
  const [busy, setBusy] = React.useState(false);

  async function submit() {
    setError(null);
    setBusy(true);
    try {
      const res = await api.post<{ caseId: string }>("/api/v1/cases", {
        title: title.trim(),
        caseNumber: caseNumber.trim() || undefined,
        description: description.trim() || undefined,
        caseType,
        caseCategory: caseCategory.trim() || undefined,
        priority,
        stateId: geo.stateId,
        districtId: geo.districtId,
        cityId: geo.cityId,
      });
      onCreated(res.caseId);
    } catch (err) {
      setError(err instanceof ApiClientError ? err.message : "Case creation failed. Please try again.");
      setConfirming(false);
    } finally {
      setBusy(false);
    }
  }

  const identityValid = title.trim().length >= 4;
  const classificationValid = !!caseType && !!priority;
  const locationValid = !!(geo.stateId && geo.districtId && geo.cityId);
  const allValid = identityValid && classificationValid && locationValid;

  if (!me) return <ErrorState message="Not authenticated." />;

  return (
    <div className="space-y-6">
      <div>
        <h1 className="flex items-center gap-2 text-xl font-semibold tracking-tight">
          <Gavel aria-hidden size={20} /> Create Case
        </h1>
        <p className="text-sm text-muted-foreground">
          A unique Case ID is generated by the system. The originating department and initial custodian are derived from
          your authenticated department.
        </p>
      </div>

      {/* SECTION 1 — Case Identity */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">1 · Case identity</CardTitle>
          <CardDescription>Title, optional official reference and description.</CardDescription>
        </CardHeader>
        <CardContent className="space-y-4">
          <div className="space-y-1.5">
            <Label htmlFor="case-title">Case title *</Label>
            <Input
              id="case-title"
              value={title}
              onChange={(e) => setTitle(e.target.value)}
              placeholder="e.g. Online financial fraud investigation"
              maxLength={200}
              aria-required="true"
            />
            {title.length > 0 && title.trim().length < 4 && (
              <FieldError message="Title must be at least 4 characters." />
            )}
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="case-number">Official case number (optional)</Label>
            <Input
              id="case-number"
              value={caseNumber}
              onChange={(e) => setCaseNumber(e.target.value)}
              placeholder="e.g. FIR/124/2026 — as issued by the originating authority"
              maxLength={64}
            />
            <p className="text-xs text-muted-foreground">
              Free-form reference. Leave empty if not applicable. Must be unique within your department.
            </p>
          </div>
          <div className="space-y-1.5">
            <Label htmlFor="case-description">Description</Label>
            <Textarea
              id="case-description"
              value={description}
              onChange={(e) => setDescription(e.target.value)}
              placeholder="Short summary of the matter…"
              rows={3}
              maxLength={4000}
            />
          </div>
        </CardContent>
      </Card>

      {/* SECTION 2 — Classification */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">2 · Classification</CardTitle>
          <CardDescription>Type and operational priority. Priority never determines legal outcome.</CardDescription>
        </CardHeader>
        <CardContent className="grid gap-4 sm:grid-cols-3">
          <div className="space-y-1.5">
            <Label>Case type *</Label>
            <Select value={caseType} onValueChange={setCaseType}>
              <SelectTrigger aria-label="Case type" aria-required="true"><SelectValue placeholder="Select type" /></SelectTrigger>
              <SelectContent>
                {(meta?.caseTypes || []).map((t) => (
                  <SelectItem key={t} value={t}>{t.replaceAll("_", " ")}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
          <div className="space-y-1.5">
            <Label>Category</Label>
            <Input value={caseCategory} onChange={(e) => setCaseCategory(e.target.value)} placeholder="Optional sub-category" maxLength={80} />
          </div>
          <div className="space-y-1.5">
            <Label>Priority *</Label>
            <Select value={priority} onValueChange={setPriority}>
              <SelectTrigger aria-label="Priority" aria-required="true"><SelectValue placeholder="Select priority" /></SelectTrigger>
              <SelectContent>
                {(meta?.casePriorities || []).map((p) => (
                  <SelectItem key={p} value={p}>{p}</SelectItem>
                ))}
              </SelectContent>
            </Select>
          </div>
        </CardContent>
      </Card>

      {/* SECTION 3 — Location */}
      <Card>
        <CardHeader>
          <CardTitle className="text-base">3 · Location</CardTitle>
          <CardDescription>
            Cascading selection — the backend validates that the city belongs to the district and the district to the state.
          </CardDescription>
        </CardHeader>
        <CardContent>
          <GeographicSelector value={geo} onChange={setGeo} />
        </CardContent>
      </Card>

      {/* SECTION 4 — Review */}
      <Card>
        <CardHeader>
          <CardTitle className="flex items-center gap-2 text-base">
            <CheckCircle2 aria-hidden size={18} className="text-emerald-600" /> 4 · Review
          </CardTitle>
          <CardDescription>Confirm before creating. The Case ID is generated after submission.</CardDescription>
        </CardHeader>
        <CardContent className="space-y-3">
          <div className="grid gap-x-6 gap-y-2 rounded-lg border bg-muted/30 p-4 text-sm sm:grid-cols-2">
            <p><span className="text-muted-foreground">Title:</span> <span className="font-medium">{title.trim() || "—"}</span></p>
            <p><span className="text-muted-foreground">Official number:</span> {caseNumber.trim() || "—"}</p>
            <p><span className="text-muted-foreground">Type:</span> {caseType ? caseType.replaceAll("_", " ") : "—"}</p>
            <p><span className="text-muted-foreground">Priority:</span> {priority || "—"}</p>
            <p><span className="text-muted-foreground">Originating department:</span> <span className="font-medium">{me.department?.name}</span></p>
            <p><span className="text-muted-foreground">Creator:</span> {me.officer.name} ({me.officer.officerId})</p>
            <p><span className="text-muted-foreground">Initial custodian:</span> {me.department?.name}</p>
            <p><span className="text-muted-foreground">Location:</span> {locationValid ? "selected" : "—"}</p>
          </div>
          <Separator />
          <FieldError message={error || undefined} />
          {!confirming ? (
            <Button disabled={!allValid} onClick={() => setConfirming(true)}>
              Continue
            </Button>
          ) : (
            <div className="flex flex-wrap gap-2">
              <Button onClick={submit} disabled={busy}>
                {busy ? "Creating…" : "Create Case"}
              </Button>
              <Button variant="outline" onClick={() => setConfirming(false)} disabled={busy}>
                Back
              </Button>
            </div>
          )}
        </CardContent>
      </Card>
    </div>
  );
}
